---
# tasks file for ./roles/ssh

# configure ssh
- name: "SSH | config ssh - global"
  ansible.builtin.include_tasks: ssh.yml
  when: ssh_only_client_setup is not defined or not ssh_only_client_setup | bool

# configure ssh per user
- name: "SSH | config ssh - per user"
  ansible.builtin.include_tasks: ssh-user.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
