---
# tasks file for ./roles/ssh

# configure ssh
- name: config ssh (and per user)
  include: ssh.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item

# configure fail2ban
- name: config fail2ban
  include: fail2ban.yml
