---
# tasks file for ./roles/ssh

# configure ssh
- name: config ssh (and per user)
  ansible.builtin.include_tasks: ssh.yml
  loop: "{{ clients | flatten(levels=1) }}"
  loop_control:
    loop_var: outer_item
