---
# tasks file for ./roles/ssh

# ------------------------------------------------------------------------------
# SSH | "get user home dir (for user {{ outer_item.name }})"
#   become: true
#   shell: >
#     getent passwd {{ outer_item.name }} | awk -F: '{ print $6 }'
#   # become_user: "{{ outer_item.name }}"
#   # shell: echo $HOME
#   changed_when: false
#   register: task_user_home

# SSH | "test (for user {{ outer_item.name }})"
#   debug: var=task_user_home.stdout_lines[0]
#   when: task_user_home is defined and task_user_home.stdout_lines is defined

# ------------------------------------------------------------------------------
- name: "SSH | user | ensures ~/.ssh/config dir exists"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    owner: "{{ outer_item.name }}"
    group: "{{ outer_item.name }}"
    mode: "0700"
  notify: Restart SSH
  tags:
    - ssh
    - ssh-user

- name: "SSH | user | copy ssh config template for user"
  become: true
  become_user: "{{ outer_item.name }}"
  ansible.builtin.template:
    src: config.config.j2
    dest: "~/.ssh/config"
    owner: "{{ outer_item.name }}"
    group: "{{ outer_item.name }}"
    mode: "0600"
  notify: Restart SSH
  tags:
    - ssh
    - ssh-user
