---
# handlers file for ./roles/ssh

- name: "SSH | restart ssh"
  become: true
  listen: restart ssh
  ansible.builtin.service:
    name: ssh
    state: restarted
    enabled: "{{ ssh_service_enabled }}"
